### ISSUE TITLE
MANPAGER=o no longer works

### ISSUE THREAD

**Issue by kseistrup** [xyproto/orbiton#14]
When I set `MANPAGER=o`, all I get when attempting to view a manpage is `o` saying “Loaded empty file: - (read only)”.

It looks like `o` is not reading from standard input, and when invoked as `o -` (some utilities regard `-` as a synonym for standard input), `o` will just create a file named `-`.

So I am wondering: Does `MANPAGER=o` really work?

Is this possibly related to #7?

----

* orbiton: 2.60
* go: 1.20.2 linux/amd64
* $TERM: xterm-256color

**Comment by xyproto** [comment]
Thanks for reporting! I'll check.

**Comment by xyproto** [comment]
It works as it should here, using Alacritty and ZSH, on Arch Linux.

I tried `MANPAGER=o man ls`.

Which terminal emulator are you using?

**Comment by kseistrup** [comment]
> Which terminal emulator are you using?

I have tried in `terminator`, `sakura`, `xterm`, `lilyterm`, and `alacritty` (!) × the shells `fish`, `bash`, and `osh`.

I have compiled `o` from the sources (from the `orbiton` package on AUR (pkgver=2.60.4-1)), but I get the same result with the pre-compiled version for x86_64 that I can download from the release section here. No difference.

My pc is running with the `en_DK.UTF-8` locale. Switching to `C` does not help.

I can see that the `man` command _is_ spawning `o`, but `o` claims that the file is empty. However, setting `MANPAGER=cat` tells me that the input is non-empty (as expected).

Running `ps | o` will show me the same “Loaded empty file: -” message at the bottom of o's “window”, and from my point of view it looks like `o` cannot or does not read anything from standard input.

(I tried the pre-compiled binary for aarch64 on an RPi just now and see the same thing (not reading standard input).)

**Comment by xyproto** [comment]
Thanks for all the testing! I'll try reproducing the issue.

**Comment by xyproto** [comment]
I can reproduce the issue now. 👍

**Comment by xyproto** [comment]
It works again here now. Please test. :)

**Comment by kseistrup** [comment]
Thanks, it works now! :+1:
