### ISSUE TITLE
Linux-static binary is not actually static

### ISSUE THREAD

**Issue by vazub** [xyproto/orbiton#15]
Not exactly a bug, but rather a misleading (unintentionally?) statement:

https://github.com/xyproto/orbiton/releases/download/v2.62.0/orbiton-2.62.0-linux_x86_64_static.tar.xz

```
$ ldd o
	/lib64/ld-linux-x86-64.so.2 (0x7f2cbac00000)
Error loading shared library libresolv.so.2: No such file or directory (needed by o)
	libc.so.6 => /lib64/ld-linux-x86-64.so.2 (0x7f2cbac00000)
```

**Comment by xyproto** [comment]
Thanks for reporting! I'll look into this.

**Comment by xyproto** [comment]
The `release.sh` script in `main` has been fixed. The release binaries for the next release should be in order.
