### ISSUE TITLE
Also support Go <1.21

### ISSUE THREAD

**Issue by yurivict** [xyproto/orbiton#18]
[here](https://github.com/xyproto/orbiton/blob/main/v2/go.mod#L3)

```
go: errors parsing go.mod:
/usr/ports/distfiles/go/editors_orbiton/orbiton-v2.64.0/go.mod:3: invalid go version '1.21.0': must match format 1.23
```

**Comment by xyproto** [comment]
Thanks for reporting! Only Go 1.21 is supported at this point.

I'll consider this as a feature request for also supporting Go 1.19 and 1.20.

**Comment by xyproto** [comment]
The `main` branch now also builds with Go 1.19 and 1.20.

Is this enough to fix the issue on your end, or would a new patch release also be needed?

**Comment by xyproto** [comment]
Created a new patch release.
