### ISSUE TITLE
2.65.7 release build failure

### ISSUE THREAD

**Issue by chenrui333** [xyproto/orbiton#19]
👋 looks like there is some issue with the 2.65.7 release which caused the following build failure

```
  ./game.go:917:26: c.ToImage undefined (type *vt100.Canvas has no field or method ToImage)
```

relates to https://github.com/Homebrew/homebrew-core/pull/157537

**Comment by xyproto** [comment]
Thank you for reporting! I will have to examine why the tests works locally but fails when the CI tests are running. I can submit a new PR for Homebrew once I have figured it out. Perhaps it is related to caching somehow.

**Comment by xyproto** [comment]
I reverted the offending commit.

I have no idea why both `go build -mod=vendor` and `go test -mod=vendor ./..` worked locally but not in the GitHub CI workflow.

**Comment by chenrui333** [comment]
Thanks @xyproto!
