### ISSUE TITLE
v2.68.0: "panic: runtime error: invalid memory address or nil pointer dereference"

### ISSUE THREAD

**Issue by razielanarki** [xyproto/orbiton#22]
after `go install`-ing the latest `v2.68.0` version , 
i get the following error when trying to run **`orbiton`**: 

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x76a04c]

goroutine 1 [running]:
main.main()
	/home/razielanarki/.cache/go/pkg/mod/github.com/xyproto/orbiton/v2@v2.68.0/main.go:242 +0x108c
```

addtional info
- `v2.67.1` works fine
- **custom env-s**:  
  `GOPATH=$XDG_CACHE_HOME/go`
  `GOBIN=$XDG_BIN_HOME`
- **go version**:  
  `go1.23.2 linux/amd64`
- **lsb_release -sd**:  
  `Ubuntu Plucky Puffin (development branch)`
- **uname -osrv**: *(latest build available from the ubuntu mainline kernel ppa)*  
   `Linux 6.11.0-061100daily20240916-generic #202409160204 SMP PREEMPT_DYNAMIC Mon Sep 16 02:29:51 UTC 2024 x86_64 GNU/Linux`

**Comment by xyproto** [comment]
Thanks for reporting! Fixed in `main`.
